POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWJyYWFtQGVtYWQuY29tIiwiaWF0IjoxNzUwNjc1ODgzLCJleHAiOjE3NTA2Nzk0ODMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.aPS67lOt6E6b-p66nVrRPY-k5gnL61a2tp1VfaeR_9Q
{
    "firstName": "Abraam",
    "lastName": "Emad",
    "email": "abraam5@emad.com",
    "password": "Password123#"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWJyYWFtQGVtYWQuY29tIiwiaWF0IjoxNzUwNjY3NzYyLCJleHAiOjE3NTA2NzEzNjIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.leKuiGEFo8mSz8amfozFuDQI9WUJ-9GZIvkX75dDAvw
{
    "users": [
        {
            "firstName": "Abraam 3",
            "lastName": "Emad 3",
            "email": "abraam3@emad.com",
            "password": "Password123#"
        },
        {
            "firstName": "Abraam 4",
            "lastName": "Emad 4",
            "email": "abraam4@emad.com",
            "password": "Password123#"
        }
    ]
}
